site_name: PCILeech Firmware Generator
site_description: Generate authentic PCIe DMA firmware from real donor hardware
site_url: https://pcileechfwgenerator.pages.dev
repo_url: https://github.com/ramseymcgrath/PCILeechFWGenerator
repo_name: ramseymcgrath/PCILeechFWGenerator
edit_uri: edit/main/site/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            docstring_style: google
            show_source: true
            show_bases: true
            show_signature_annotations: true
            show_if_no_docstring: true
            inherited_members: false
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: spacy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quick-start.md
  - Documentation:
    - Architecture:
      - Template Architecture: template-architecture.md
      - Configuration Space Shadow: config-space-shadow.md
      - Dynamic Device Capabilities: dynamic-device-capabilities.md
    - Usage:
      - Device Cloning: device-cloning.md
      - Manual Donor Dump: manual-donor-dump.md
      - Firmware Uniqueness: firmware-uniqueness.md
      - TUI Interface: tui-readme.md
    - Reference:
      - Supported Devices: supported-devices.md
      - No Fallback Policy: no-fallback-policy.md
      - Troubleshooting: troubleshooting.md
  - API Reference:
    - Overview: api/index.md
    - CLI: api/cli.md
    - Device Clone: api/device_clone.md
    - PCI Capability: api/pci_capability.md
    - File Management: api/file_management.md
    - Templating: api/templating.md
    - Vivado Handling: api/vivado_handling.md
    - TUI: api/tui.md
    - Utils: api/utils.md
  - Development:
    - Development Guide: development.md
    - Contributing: ../CONTRIBUTING.rst
    - Code of Conduct: ../CODE_OF_CONDUCT.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ramseymcgrath/PCILeechFWGenerator
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/429866199833247744

copyright: Copyright &copy; 2025 Ramsey McGrath
